# Generated by Django 3.0.1 on 2020-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
