# Generated by Django 3.0.1 on 2020-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='johndoe@mail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
